language:
  - c

compiler:
  - gcc


os:
  - linux

addons:
  apt:
    sources:
      - george-edison55-precise-backports # cmake 3.2.3 / doxygen 1.8.3
    packages:
      - cmake
      - cmake-data


script:

  - mkdir _build_pnl
  - cd _build_pnl
  - cmake -DCMAKE_BUILD_TYPE=Release ..
  - make
  - make test

notifications:
  email:
    on_success: never
    on_failure: always



