language:
  - c

compiler:
  - gcc


os:
  - linux

sudo: required

dist: trusty



script:

  - mkdir _build_pnl
  - cd _build_pnl
  - cmake -DCMAKE_BUILD_TYPE=Release ..
  - make
  - make test

notifications:
  email:
    on_success: never
    on_failure: always



